groups:
- name: isc_reserved
  rules:
  - alert: iris_system_alerts
    annotations:
      description: 'WARNING: Removing this rule will disable the handling of InterSystems
        IRIS System Monitor text alerts!'
    expr: (idelta(iris_system_alerts_log[5m]) != 0) or (iris_system_alerts_new > 0)
- name: "1"
  rules: []
- name: "2"
  rules: []
- name: "3"
  rules:
  - alert: PYTHON ALERT
    annotations:
      description: PYTHON ALERT {{ $value }}
    expr: EventLog_python{cluster="3"} > 0
    labels:
      severity: critical
  - alert: MATTHIEU
    annotations:
      description: MATTHIEU {{ $value }}
    expr: EventLog_python{cluster="3"} != 0
    labels:
      severity: warning
- name: "4"
  rules: []
- name: "5"
  rules: []

